# Change these first
owner: internetofwater
repo: uptime.geoconnex.us

# Add your sites here
sites:
  - name: Geoconnex Persistent Identifier Service
    slug: pid-service
    url: https://pids.geoconnex.us
    icon: https://yourls.org/assets/images/favicon.svg
  - name: Geoconnex Reference Feature Service
    slug: feature-service
    url: https://reference.geoconnex.us/collections
    icon: https://pygeoapi.io/favicon.ico
  - name: Geoconnex Knowledge Graph
    slug: knowledge graph
    url: https://graph.geoconnex.us
    method: POST
    headers:
      - "Content-Type: application/sparql-query"
      - "Accept: application/sparql-results+json"
    body: |
      ASK {
        ?s ?p ?o
      }

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.geoconnex.us
  logoUrl: https://reference.geoconnex.us/static/img/logo.png
  favicon: https://reference.geoconnex.us/static/img/favicon.ico
  name: Uptime
  introTitle: "**Geoconnex Service Status**"
  introMessage: >
    This page provides real-time availability and historical uptime for the
    Geoconnex platform, including the PID Service and Reference Feature Service.
  navbar:
    - title: Status
      href: /
    - title: Docs
      href: https://docs.geoconnex.us

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
